0:
  src: "/images/companyImages/values-images/values_image1.webp"
  title: "Results-driven"
  description: "We are committed to delivering measurable improvements for our clients through focused and objective-driven IoT solutions."
  height: 756px
1:
  src: "/images/companyImages/values-images/values_image2.webp"
  title: "Customer focus"
  description: "Our customers are at the core of our business; we tailor our IoT solutions to meet their unique needs and exceed expectations."
  height: 756px
2:
  src: "/images/companyImages/values-images/values_image3.webp"
  title: "Growth and Self-improvement"
  description: "Continuous learning and staying ahead of industry trends enable us to offer cutting-edge IoT solutions."
  height: 756px
3:
  src: "/images/companyImages/values-images/values_image4.webp"
  title: "Expertise"
  description: "We uphold the highest standards of conduct and integrity, ensuring reliable and high-quality IoT solutions."
  height: 756px
4:
  src: "/images/companyImages/values-images/values_image5.webp"
  title: "Team work"
  description: "At ThingsBoard, we thrive on collaboration, leveraging each team member's strengths to deliver innovative IoT solutions."
  height: 756px
5:
  src: "/images/companyImages/values-images/values_image6.webp"
  title: "Volunteering"
  description: "We give back to the community through various initiatives, reinforcing our commitment to making a positive impact."
  height: 756px

